version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "api@rest.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
#  migrate:
#    image: migrate/migrate:4
#    volumes:
#      - ./migrations:/migrations
#    entrypoint:
#      [
#        "migrate",
#        "-path",
#        "/migrations",
#        "-database",
#        "postgres://postgres:postgres@postgres:5432/personalities?sslmode=disable",
#      ]
#    command: ["up"]
#    depends_on:
#      - postgres

volumes:
  db:
    driver: local