### Send POST request with json body
POST http://localhost:5000/students
Content-Type: application/json

{
  "name": "Atila",
  "rg": "44034125",
  "cpf": "36833586899"
}


### Send GET request
GET http://localhost:5000/students
Content-Type: application/json

### Send GET request with student id
GET http://localhost:5000/students/10
Content-Type: application/json

### Send DELETE request with student id
DELETE http://localhost:5000/students/3
Content-Type: application/json
